- .github/workflows/check.yml
> build(ci): nix flake check workflow

- flake.lock
- flake.nix
> build: pin nixpkgs to avoid later broken rustfmt

- api.nix
- crates/pr-tracker-api/src/lib.rs
- flake.nix
This fixes https://github.com/molybdenumsoftware/pr-tracker/issues/13
> build(api): use clippy

- crates/pr-tracker-api/src/lib.rs
- crates/pr-tracker-api/tests/test.rs
- crates/util/src/bin/db-repl.rs
- crates/util/src/bin/sqlx-prepare.rs
- crates/util/src/lib.rs
- refactor: introduce a test context
- feature: run migrations on api startup
> api migrates on startup

- api.nix
- flake.nix
- packages/api/package.nix
- packages/default.nix
- refactor(flake): extract cargoWorkspaceSrc
- refactor(flake): create a packages directory
- refactor(flake): mv buildInputs,cargoWorkspaceSrc
- refactor(flake): autodiscover packages by-name
- refactor(flake): remove unused binding
> some flake refactors

- Cargo.lock
- crates/fragile-child/Cargo.toml
- crates/fragile-child/src/lib.rs
- crates/util/Cargo.toml
- crates/util/src/lib.rs
> test: kill postgres on ready timeout

- crates/util/src/lib.rs
Apparently postgres will create sockets before it's actually ready for
clients to talk to it! Weird, but we have a better way of doing this
thanks to the `NOTIFY_SOCKET` protocol we just learned about.
> test: reliable waiting for postgres to start up

- crates/util/src/lib.rs
- test: don't test on darwin
- test: reliable waiting for postgres to start up
> better postgres waiting

- flake.nix
- modules/api.nix
- nixos-tests/api.nix
- packages/api/package.nix
- packages/default.nix
- refactor(flake): pass lib explicitly everywhere
- refactor(flake): sort imports Co-authored-by: Shahar "Dawn" Or <mightyiampresence@gmail.com>
> imports refactor

- packages/api/package.nix
- packages/default.nix
> refactor(flake): rm unused buildInputs

- flake.lock
- flake.nix
- packages/api/package.nix
- packages/default.nix
> build(flake): use crane to build rust crates

- crates/api/tests/test.rs
- flake.lock
- flake.nix
- packages/default.nix
> build(flake): fenix

- .github/workflows/check.yml
- flake.nix
- chore(deps): bump nixpkgs
- build: enforce no url literals
> build: enforce no url literals

- crates/api/src/lib.rs
- crates/api/tests/test.rs
- crates/store/src/lib.rs
> refactor(store): eliminate i32 pr num at boundary

- crates/store/src/lib.rs
> chore: fix some private api docs

- crates/store/src/lib.rs
> chore: rm some unused fn

- crates/api/src/lib.rs
> refactor(api): flatten a nested match

- crates/api/src/lib.rs
- crates/store/src/lib.rs
- crates/util/src/lib.rs
> style: replace some qualified paths with use

- crates/api/src/lib.rs
- crates/store/src/lib.rs
> style(store): rename to GhNumberNonPositiveError

- Cargo.lock
- Cargo.toml
- crates/api/Cargo.toml
- crates/api/src/lib.rs
- crates/store/Cargo.toml
- crates/store/src/lib.rs
> refactor: implement Error for error types

- Cargo.lock
- Cargo.toml
- crates/api/Cargo.toml
- crates/fetcher/Cargo.toml
- crates/store/Cargo.toml
- crates/util/Cargo.toml
> chore: bump versions to v1.0.0

- flake.nix
- packages/default.nix
- packages/fetcher/package.nix
- style: use env var name for GITHUB_GRAPHQL_SCHEMA
- build(flake): no GITHUB_GRAPHQL_SCHEMA in api crate build
> github graphql schema

- packages/default.nix
> build(flake): inline commonArgs

- Cargo.toml
Arbitrary choice, trading off binary size for debug-ability.
> feat: debug symbols in release profile

- flake.nix
- modules/api/package.nix
- nixos-tests/api/package.nix
- packages/default.nix
- build: extract cargo artifacts
- feat: add `options.services.pr-tracker-api.package` option
> dont strip

- Cargo.lock
- crates/fetcher/Cargo.toml
- crates/fetcher/src/main.rs
- modules/fetcher/package.nix
- nixos-tests/fetcher/package.nix
> feat: pr-tracker-fetcher and nixos module

- packages/fetcher/package.nix
> fix(flake): fetcher wrapper with git in PATH

- crates/fetcher/src/lib.rs
- crates/store/src/lib.rs
> perf(fetcher): bulk fetch all landed PRs before generating landings

- crates/fetcher/src/main.rs
- modules/fetcher/package.nix
- fix(flake): fetcher module correct systemd CacheDirectory option
- feat(fetcher)!: remove cacheDir option
> fetcher cache directory

- Cargo.lock
- Cargo.toml
- crates/api/Cargo.toml
- crates/api/test-util.rs
- crates/db-context/Cargo.toml
- crates/db-context/src/lib.rs
- crates/fetcher/Cargo.toml
- crates/fetcher/src/test.rs
- crates/util/src/bin/db-repl.rs
- crates/util/src/bin/sqlx-prepare.rs
- crates/util/src/lib.rs
> chore: extract DatabaseContext into its own crate

- Cargo.lock
- crates/fetcher/src/lib.rs
- crates/store/Cargo.toml
- crates/store/src/lib.rs
> perf(fetcher): batch upsert landings

- .gitignore
> chore: gitignore /result

- .github/workflows/update-flake-lock.yml
> ci: workflow for bumping flake inputs

- README.md
> docs: initial readme content

- modules/api/package.nix
- modules/fetcher/package.nix
> docs: revise nixos module enable option desriptions

- modules/fetcher/package.nix
- nixos-tests/fetcher/package.nix
- nixos-tests/fetcher/socket-db.nix
- nixos-tests/fetcher/tcp-db.nix
> fix(flake): services.pr-tracker-fetcher.dbPasswordFile not required

- attrsToURLParams.nix
- flake.nix
- modules/api/package.nix
- modules/fetcher/package.nix
- nixos-tests/api/package.nix
- nixos-tests/api/socket-db.nix
- nixos-tests/api/tcp-db.nix
- **refactor(flake): extract attrsToURLParams**
- **feat(flake)!: in api replace databaseUrl with dbUrlParams and dbPasswordFile**
> api passwordfile

- .github/workflows/docs.yml
- Cargo.lock
- Cargo.toml
- README.md
- crates/api-config/Cargo.toml
- crates/api-config/PORT.md
- crates/api-config/src/lib.rs
- crates/api/Cargo.toml
- crates/api/src/main.rs
- crates/fetcher-config/BRANCH_PATTERNS.md
- crates/fetcher-config/Cargo.toml
- crates/fetcher-config/GITHUB_REPO_NAME.md
- crates/fetcher-config/GITHUB_REPO_OWNER.md
- crates/fetcher-config/GITHUB_TOKEN.md
- crates/fetcher-config/src/lib.rs
- crates/fetcher/Cargo.toml
- crates/fetcher/src/main.rs
- modules/api/package.nix
- modules/fetcher/package.nix
- packages/default.nix
- packages/docs/package.nix
> docs: fetcher and api environment variables

- modules/api/package.nix
- modules/common.nix
- modules/fetcher/package.nix
> docs(flake): pkgsText in services.pr-tracker-*.package

- .github/workflows/docs.yml
- README.md
- filterOptions-check.nix
- filterOptions.nix
- flake.lock
- flake.nix
- modules/api.nix
- modules/common.nix
- modules/fetcher.nix
- packages/default.nix
- packages/nixos-modules-manual/manual.md
- packages/nixos-modules-manual/package.nix
- packages/program-docs/package.nix
- **refactor(flake): rename documentation package**
- **docs(flake): nixos modules manual**
> nixos module docs

- .github/workflows/update-flake-lock.yml
> build(ci): token for flake inputs update

- Cargo.toml
- crates/api-config/Cargo.toml
- crates/api/Cargo.toml
- crates/db-context/Cargo.toml
- crates/fetcher-config/Cargo.toml
- crates/fetcher/Cargo.toml
- crates/store/Cargo.toml
- crates/util/Cargo.toml
> chore: crates share version

- README.md
> docs: explain versioning

- .github/workflows/check.yml
- .github/workflows/generate-app-token.yml
- .github/workflows/release.yml
- .github/workflows/update-flake-lock.yml
- .releaserc.yaml
> build(ci): automatic releases

- .github/workflows/release.yml
- .releaserc.yaml
> build(ci): do not use semantic-release-cargo

- Cargo.toml
- crates/db-context/Cargo.toml
- crates/fragile-child/Cargo.toml
- **chore: no version for cargo path-dependencies**
- **chore: fragile child inherits workspace version**
> some cargo workspace chores

- .github/workflows/release.yml
- .releaserc.yaml
- flake.nix
- release/default.nix
- release/semantic-release-with-plugins/package-lock.json
- release/semantic-release-with-plugins/package.json
- **build(ci): rewrite release in nix**
- **build(ci): semantic release no dry run**
> release workflow in flake

- README.md
- **docs: footnote on what merge commit means**
- **docs: remove redundant s**
> not have to be merge commit

- README.md
> docs: consistent history assumption

- modules/api.nix
- modules/fetcher.nix
- nixos-tests/api/default-package.nix
- nixos-tests/api/socket-db.nix
- nixos-tests/api/tcp-db.nix
- nixos-tests/fetcher/default-package.nix
- nixos-tests/fetcher/socket-db.nix
- nixos-tests/fetcher/tcp-db.nix
> feat(flake)!: services.pr-tracker attrset

- packages/default.nix
> refactor(flake): simplify crates source filtering

- README.md
> docs: alternatives and vision

- flake.nix
- **chore(flake)!: rm empty nixosModules.common**
> chore(flake)!: rm empty nixosModules.common

- .github/workflows/docs.yml
> build: docs workflow runs on pull request, but only deploys on main

- .gitignore
- Cargo.lock
- Cargo.toml
- crates/api/test-util.rs
- crates/db-context/Cargo.toml
- crates/db-context/src/lib.rs
- crates/fetcher/Cargo.toml
- crates/fetcher/src/test.rs
- crates/util/src/bin/db-repl.rs
- crates/util/src/bin/sqlx-prepare.rs
> chore: utils-db-repl sends db logs to file

- crates/api/src/lib.rs
> refactor: not reusing ForPrError in LandedError

- .github/workflows/check.yml
- .github/workflows/docs.yml
- .github/workflows/release.yml
- .github/workflows/update-flake-lock.yml
- flake.nix
Co-authored-by: Robert James Hernandez <rob@sarcasticadmin.com>
> chore: nix pipe operators

- .github/workflows/check.yml
- .github/workflows/docs.yml
- .github/workflows/release.yml
This reverts commit 904db604929dd10b721a6962d702e576059e70cf.
> Revert "ci: rm magic-nix-cache 😢"
